version: '3.8'
name: ${APP_NAME}

networks:
  app-network:
    driver: bridge
  frontend:
    driver: bridge
    external: false

services:
  backend-api:
    image: ${IMAGE:-example/image:latest}
    restart: unless-stopped
    environment:
      - APP_API_KEY=${APP_API_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - NODE_ENV=${NODE_ENV:-production}
      - ENV_NAME=${ENV_NAME:-default}
    ports:
      - '${PORT:-3000}:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-api
    networks:
      - app-network
      - frontend