version: '3.8'
name: ${APP_NAME:-backend}

networks:
  backend-network:
    driver: bridge
  frontend:
    driver: bridge
    external: false

services:
  backend-api:
    image: ${IMAGE_REPO:-ghcr.io/example/backend}:${VERSION:-latest}
    restart: unless-stopped
    environment:
      - APP_API_ENDPOINT=${APP_API_ENDPOINT}
      - APP_CONFIG_VALUE=${APP_CONFIG_VALUE}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - APP_CORS_ORIGINS=${APP_CORS_ORIGINS}
      - NODE_ENV=${NODE_ENV:-production}
      - ENV_NAME=${ENV_NAME:-default}
    ports:
      - '${PORT:-3000}:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  nginx:
    image: nginx:stable-alpine
    # No hardcoded container name to allow blue/green environments
    restart: unless-stopped
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-api
    networks:
      - backend-network
      - frontend
